echo " The command is $0"
echo "The no.of arguments passed $#"
echo "The parameters passed $*"
echo "The parameters passed $@"
echo "The first argument $1"
echo " second argument $2"
echo " Third argument $3"
